all::  Attribut.class AttributProto.class AttributPool.class DefIni.class Entity.class  EntityProto.class Resource.class ResourcePool.class



clean::
	rm *.class 

%.class: %.java
	javac   -classpath ../../../.. -deprecation -g  $*.java

