all:: Arrow.class                     PPAbout.class        PPgFrameLog.class        PPgIntField.class    PPgSliderDouble.class  PPgTextEditorChild.class \
FontChooserComboBox.class       PPgAppli.class       PPgFrameTable.class      PPgJFrame.class      PPgSliderField.class   PPgTextStream.class \
FontComboBox.class              PPgCanvas.class      PPgGraphicsHelper.class  PPgLogin.class       PPgSlider.class        PPgTrayIcon.class \
FrameEditObjectInterface.class  PPgField.class       PPgHelpChild.class       PPgMenuGrid.class    PPgTable.class         PPgWinUtils.class \
FrameEditObject.class           PPgFloatField.class  PPgInputField.class      PPgPanelTable.class  PPgTableLine.class     PPHtml.class \
JFontChooser.class              PPgFrameChild.class  PPgInterfaceAppli.class  PPgSelectBox.class   PPgTerm.class          PPTraceTerm.class

clean::
	rm  -f *.class 

%.class: %.java
	javac   -classpath ../../../.. -deprecation -g  $*.java


