all::  Gamer.class GamerHuman.class Entity.class EntityMobil.class  PrototypeXmlLoader.class PrototypeCase.class  PrototypeBuilding.class InterfaceHandlerXmlNode.class PrototypeUnit.class PrototypeWeapon.class Weapon.class Arsenal.class CommandIcon.class ActionEntityMobilRepair.class ActionEntityInternalRepair.class  ActionEntity.class ActionEntityMove.class DecorCase.class DecorCarte.class PathCase.class PathCarte.class PanelBox.class GamePanel.class PanelMain2D.class PanelMiniMap.class PanelOrder.class PanelInfoSelect.class FrameGamer2D.class RenderBase.class Render2D.class RenderMiniMap.class RenderInfoSelect.class RenderOrder.class World.class PathFinder.class MathUtils.class XmlLoader.class Util.class Ressource.class RessourceTable.class AnimAll.class AnimAction.class AnimActionSeq.class AnimActionMap.class AnimSeq.class Bmp.class

clean::
	/usr/bin/rm *.class *.jar


%.class: %.java
	javac   -classpath ../../..  -deprecation -g $*.java
 
