all::
	cd PPgData;	        make ;cd ..;\
	cd PPgG3d;  	make ;cd ..;\
	cd PPgGame;  	make ;cd ..;\
	cd PPgRts;      make ;cd ..;\
	cd PPgSFX;       make ;cd ..;\

clean::
	cd PPgData;	make clean ;cd ..;\
	cd PPgG3d;  	make clean ;cd ..;\
	cd PPgGame;  	make clean ;cd ..;\
	cd PPgRts;      make clean ;cd ..;\
	cd PPgSFX;      make clean ;cd ..;\

jar::
	cd PPgData;	        make jar ;cd ..;\
	cd PPgG3d;  	make jar ;cd ..;\
	cd PPgGame;  	make jar ;cd ..;\
	cd PPgRts;       make jar ;cd ..;\
	cd PPgSFX;       make jar ;cd ..;\

install::
	cd PPgData;	        make install ;cd ..;\
	cd PPgG3d;  	make install ;cd ..;\
	cd PPgGame;  	make install ;cd ..;\
	cd PPgRts;      make install ;cd ..;\
	cd PPgSFX;       make install ;cd ..;\


.PHONY: clean
