all::
	cd PPg;	        make ;cd ..;\
	cd PPgGame;  	make ;cd ..;\
	cd PPgGame3d;  	make ;cd ..;\
	cd PPgTestGame3d;make ;cd ..;\
	cd GameSwarm;   make ;cd ..;\
	cd Jixmu;       make ;cd ..;\
	cd PPgEdImg;    make ;cd ..;\
	cd SqlTools; 	make ;cd ..;\
	cd TestSwarm; 	make ;cd ..;\
	cd TestSwarm2; 	make ;cd ..;\

clean::
	cd PPg;	        make clean ;cd ..;\
	cd PPgGame;  	make clean ;cd ..;\
	cd PPgGame3d;  	make clean ;cd ..;\
	cd PPgTestGame3d;make clean;cd ..;\
	cd GameSwarm;   make clean ;cd ..;\
	cd Jixmu;       make clean ;cd ..;\
	cd PPgEdImg;    make clean ;cd ..;\
	cd SqlTools; 	make clean ;cd ..;\
	cd TestSwarm; 	make clean ;cd ..;\
	cd TestSwarm2; 	make clean ;cd ..;\

jar::
	cd PPg;	        make jar ;cd ..;\
	cd PPgGame;  	make jar ;cd ..;\
	cd PPgGame3d;  	make jar;cd ..;\
	cd PPgTestGame3d;make jar;cd ..;\
	cd GameSwarm;   make jar ;cd ..;\
	cd Jixmu;       make jar ;cd ..;\
	cd PPgEdImg;    make jar ;cd ..;\
	cd SqlTools; 	make jar ;cd ..;\
	cd TestSwarm; 	make jar ;cd ..;\
	cd TestSwarm2; 	make jar ;cd ..;\

install::
	cd PPg;	        make install ;cd ..;\
	cd PPgGame;  	make install ;cd ..;\
	cd PPgGame3d;  	make install;cd ..;\
	cd PPgTestGame3d;make install;cd ..;\
	cd GameSwarm;   make install ;cd ..;\
	cd Jixmu;       make install ;cd ..;\
	cd PPgEdImg;    make install ;cd ..;\
	cd SqlTools; 	make install ;cd ..;\
	cd TestSwarm; 	make install ;cd ..;\
	cd TestSwarm2; 	make install ;cd ..;\


.PHONY: clean
