all::	FontChooserComboBox.class       PPgAppli.class               PPgFrameTable.class      PPgJFrame.class        PPgSlider.class      PPgWinUtils.class FontComboBox.class              PPgCanvas.class              PPgGraphicsHelper.class  PPgMenuGrid.class      PPgTable.class       PPHtml.class FrameEditObjectInterface.class  PPgField.class               PPgHelpChild.class       PPgPanelTable.class    PPgTableLine.class   PPTraceTerm.class FrameEditObject.class           PPgFloatField.class          PPgInputField.class      PPgSelectBox.class     PPgTerm.class JFontChooser.class              PPgFrameChild.class          PPgInterfaceAppli.class  PPgSliderDouble.class  PPgTextStream.class PPAbout.class   PPgIntField.class        PPgSliderField.class   PPgTrayIcon.class PPgFrameLog.class Arrow.class

clean::
	rm *.class 

%.class: %.java
	javac   -classpath ../../../.. -deprecation -g  $*.java


