all:: Ressources.class SimplePanel.class GamerEvent.class PPgSwarm.class MyGamer.class MyWorld.class   SpriteType.class  WeaponType.class Weapon.class InterfaceUnit.class ShipBase.class ShipType.class FactoryActor.class Ship.class ShipLaser.class ShipMissile.class ShipField.class  Fleet.class FleetGamer.class FleetEnemy.class SingleShip.class FactoryLevel.class LevelAsteroid.class  LevelAsteroid2.class LevelTest.class LevelBigShip.class LevelBase.class
 

clean::
	rm *.class 

%.class: %.java
	javac   -classpath ../../../.. -deprecation -g  $*.java
 
